// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKTN20mArfGpCiYJuiuvO7mKdL7u6n5ew',
    appId: '1:200427143734:web:0b09734e663b18907b4e97',
    messagingSenderId: '200427143734',
    projectId: 'fir-18867',
    authDomain: 'fir-18867.firebaseapp.com',
    storageBucket: 'fir-18867.firebasestorage.app',
    measurementId: 'G-CW0YB56X1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0TFWZIQJ4aEgGYGGlS2May3KLCk8ThDk',
    appId: '1:200427143734:android:77c3be420dcd81917b4e97',
    messagingSenderId: '200427143734',
    projectId: 'fir-18867',
    storageBucket: 'fir-18867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR9JDWsBSewXTSQR891j-fhoRXylBEvDo',
    appId: '1:200427143734:ios:c4e882310ca151577b4e97',
    messagingSenderId: '200427143734',
    projectId: 'fir-18867',
    storageBucket: 'fir-18867.firebasestorage.app',
    iosBundleId: 'com.example.passwordManagerBtT5Cloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR9JDWsBSewXTSQR891j-fhoRXylBEvDo',
    appId: '1:200427143734:ios:c4e882310ca151577b4e97',
    messagingSenderId: '200427143734',
    projectId: 'fir-18867',
    storageBucket: 'fir-18867.firebasestorage.app',
    iosBundleId: 'com.example.passwordManagerBtT5Cloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKTN20mArfGpCiYJuiuvO7mKdL7u6n5ew',
    appId: '1:200427143734:web:0b09734e663b18907b4e97',
    messagingSenderId: '200427143734',
    projectId: 'fir-18867',
    authDomain: 'fir-18867.firebaseapp.com',
    storageBucket: 'fir-18867.firebasestorage.app',
    measurementId: 'G-CW0YB56X1P',
  );
}
