import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

import 'firebase_options.dart'; // Generated by flutterfire configure
import 'screens/login_screen.dart';
import 'screens/master_lock_screen.dart';
// Screen Imports - Ensure these files exist in your lib/screens/ folder
import 'screens/splash_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase for Windows/Android
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'T5 Password Manager Cloud',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.teal,
          brightness:
              Brightness.dark, // Modern dark theme for password managers
        ),
      ),
      home: const AuthWrapper(),
    );
  }
}

class AuthWrapper extends StatefulWidget {
  const AuthWrapper({super.key});

  @override
  State<AuthWrapper> createState() => _AuthWrapperState();
}

class _AuthWrapperState extends State<AuthWrapper> {
  bool _showSplash = true;
  final FlutterSecureStorage _storage = const FlutterSecureStorage();

  @override
  void initState() {
    super.initState();
    _handleSplashTimer();
  }

  // Timer to show splash screen for 3 seconds
  void _handleSplashTimer() async {
    await Future.delayed(const Duration(seconds: 5));
    if (mounted) {
      setState(() {
        _showSplash = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    // 1. Show Splash Screen if timer hasn't finished
    if (_showSplash) {
      return const SplashScreen();
    }

    // 2. Monitor Firebase Auth state
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, authSnapshot) {
        if (authSnapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // If User is logged into Firebase
        if (authSnapshot.hasData) {
          // 3. Monitor Local Master Password state
          return FutureBuilder<String?>(
            future: _storage.read(key: 'master_key'),
            builder: (context, storageSnapshot) {
              if (storageSnapshot.connectionState == ConnectionState.waiting) {
                return const Scaffold(
                  body: Center(child: CircularProgressIndicator()),
                );
              }

              // Case A: User logged in but has NOT set a Master Password yet
              if (storageSnapshot.data == null) {
                return const MasterLockScreen(isSetupMode: true);
              }
              // Case B: User logged in and Master Password exists -> Show Unlock screen
              else {
                return const MasterLockScreen(isSetupMode: false);
              }
            },
          );
        }

        // 4. If User is NOT logged into Firebase
        return const LoginScreen();
      },
    );
  }
}
